name: Inputs Test

on: 
  workflow_dispatch:
    inputs:
      BuildType: 
        description: "Unreal Build Type"
        type: choice
        required: true
        default: Development
        options:
          - Development
          - Debug
          - Shipping
jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      - name: "run script"
        run: |
          echo "The build type is: ${{inputs.environment.BuildType}}"